name: Test
on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-16.04
    env:
      CLIENT_FOLDER: ./client
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: yarn install --frozen-lockfile --cwd ${env.CLIENT_FOLDER}
      - name: Unit Tests
        run: yarn --cwd ${env.CLIENT_FOLDER} test:unit
      - name: E2E tests
        run: yarn --cwd ${env.CLIENT_FOLDER} test:e2e --headless
